name: SuperBans
description: Complete banning solution for Bukkit
version: maven-version-number
author: cedeel
main: be.darnell.superbans.SuperBans

commands:
  ################
  # BASE COMMAND #
  ################
  superbans:
    description: The commands for interfacing with SuperBans
    aliases: [sb]
    usage: /<command> [section] [options]...
  #################
  # GENERAL USAGE #
  #################
  ban:
    description: Ban a player
    usage: /<command> {player} [-s|-a] {reason}
  tempban:
    description: Temporarily ban a player
    usage: /<command> {player} [-s|-a] {amount} {sec|min|hour|day} {reason}
  ipban:
    description: Ban a player by IP address
    usage: /<command> {player} [-s|-a] {reason}
  tempipban:
    description: Temporarily ban a player by IP address
    usage: /<command> {player} [-s|-a] {amount} {sec/min/hour/day} {reason}
  permaban:
    description: A very sticky ban
    usage: /<command> {player} [-s|-a] {reason}
  unban:
    description: Unban a player
    usage: /<command> {player}
  warn:
    description: Warn a player
    usage: /<command> {player} [-s|-a] {reason}
  kick:
    description: Kick a player
    usage: /<command> {player / *} [-s|-a] {reason}
  #################
  # INFORMATIONAL #
  #################
  checkban:
    description: Check if a player is banned
    usage: /<command> [player]
  banlist:
    description: Get a list of infractions by a player
    usage: /<command> {player}
  checkip:
    description: Check a player's IP address
    usage: /<command> {player}
  dupeip:
    description: Check a player's IP address against all players
    usage: /<command> {player}
# Management #
  sbstatus:
    description: Shows statistics about SuperBans
    usage: /<command>
  sbreload:
    description: Reload the bans
    usage: /<command>
  editban:
    description: Edit a ban
    usage: /<command> {list|load|id|save|view|reason|time|cancel|help}
  exportbans:
    description: Export bans to default text files
    usage: /<command>
  importbans:
    description: Import bans from default text files
    usage: /<command>
permissions:
  superbans.tempban:
    description: Allows temporary banning of players
  superbans.ipban:
    description: Allows banning of players by IP address
  superbans.tempipban:
    description: Allows temporary banning of players by IP address
  superbans.permaban:
    description: Allows the permanent banning of players
  superbans.kick:
    description: Allows kicking of players
  superbans.kick.all:
    description: Allows kicking of everyone besides the issuing player
    children:
      superbans.kick: true
  superbans.warn:
    description: Warn a player
  superbans.banlist:
    description: Get a list of previous infractions
  superbans.checkban:
    description: Check if a player is banned
  superbans.checkip:
    description: Check a player's last known IP
  superbans.dupeip:
    description: Check for IP address duplicates of a player
  superbans.status:
    description: Allows a player to check the status of SuperBans
  superbans.reload:
    description: Reload ban database
  superbans.editban:
    description: Edit a ban
  superbans.import:
    description: Import bans from a plain text file
  superbans.export:
    description: Export bans to a plain text file
  superbans.override.*:
    description: Allows a player to override commands
    children:
      superbans.override.ban: true
      superbans.override.ipban: true
      superbans.override.kick: true
      superbans.override.kick: true
      superbans.override.kick.all: true
      superbans.override.permaban: true
      superbans.override.tempban: true
      superbans.override.tempipban: true
      superbans.override.warn: true
      superbans.override.dupeip: true
  superbans.override.ban:
    description: Allows a player to override bans
  superbans.override.ipban:
    description: Allows a player to override IP bans
  superbans.override.kick:
    description: Allows a player to override kicks
  superbans.override.kick.all:
    description: Allows a player to override kickall
  superbans.override.permaban:
    description: Allows a player to override a permaban
  superbans.override.tempban:
    description: Allows a player to override a temporary ban
  superbans.override.tempipban:
    description: Allows a player to override a temporary IP ban
  superbans.override.warn:
    description: Allows a player to override a warning
  superbans.override.dupeip:
    default: op
    description: Allows a player to override the dupe IP check on login