name: ${name}
description: Complete banning solution for Bukkit
version: ${version}
author: cedeel
main: be.darnell.superbans.SuperBans

commands:
  ################
  # BASE COMMAND #
  ################
  superbans:
    description: The commands for interfacing with SuperBans
    aliases: [sb]
    usage: /<command> [section] [options]...
  #################
  # GENERAL USAGE #
  #################
  ban:
    description: Ban a player
    usage: /<command> {player} [-s|-a] {reason}
  tempban:
    description: Temporarily ban a player
    usage: /<command> {player} [-s|-a] {amount} {sec|min|hour|day} {reason}
  ipban:
    description: Ban a player by IP address
    usage: /<command> {player} [-s|-a] {reason}
  tempipban:
    description: Temporarily ban a player by IP address
    usage: /<command> {player} [-s|-a] {amount} {sec/min/hour/day} {reason}
  permaban:
    description: A very sticky ban
    usage: /<command> {player} [-s|-a] {reason}
  unban:
    description: Unban a player
    usage: /<command> {player}
  warn:
    description: Warn a player
    usage: /<command> {player} [-s|-a] {reason}
  kick:
    description: Kick a player
    usage: /<command> {player / *} [-s|-a] {reason}
  #################
  # INFORMATIONAL #
  #################
  checkban:
    description: Check if a player is banned
    usage: /<command> [player]
  banlist:
    description: Get a list of infractions by a player
    usage: /<command> {player}
  checkip:
    description: Check a player's IP address
    usage: /<command> {player}
  dupeip:
    description: Check a player's IP address against all players
    usage: /<command> {player}
# Management #
  sbstatus:
    description: Shows statistics about SuperBans
    usage: /<command>
  sbreload:
    description: Reload the bans
    usage: /<command>
  editban:
    description: Edit a ban
    usage: /<command> {list|load|id|save|view|reason|time|cancel|help}
  exportbans:
    description: Export bans to default text files
    usage: /<command>
  importbans:
    description: Import bans from default text files
    usage: /<command>